CREATE TABLE IF NOT EXISTS USERS(
    id INT NOT NULL AUTO_INCREMENT,
    is_moderator TINYINT NOT NULL,
    reg_time DATETIME NOT NULL,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    code VARCHAR(255),
    photo TEXT,

    PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS POSTS(
    id INT NOT NULL AUTO_INCREMENT,
    is_active TINYINT NOT NULL,
    moderation_status ENUM("NEW", "ACCEPTED", "DECLINED") NOT NULL,
    moderator_id INT,
    user_id INT NOT NULL,
    time DATETIME NOT NULL,
    title VARCHAR(255) NOT NULL,
    text TEXT NOT NULL,
    view_count INT NOT NULL,

    PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS POST_VOTES(
    id INT NOT NULL AUTO_INCREMENT,
    user_id INT NOT NULL,
    post_id INT NOT NULL,
    time DATETIME NOT NULL,
    value TINYINT NOT NULL,

    PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS TAGS(
    id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,

    PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS TAG2POST(
    id INT NOT NULL AUTO_INCREMENT,
    post_id INT NOT NULL,
    tag_id INT NOT NULL,

    PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS POST_COMMENTS(
    id INT NOT NULL AUTO_INCREMENT,
    parent_id INT,
    post_id INT NOT NULL,
    user_id INT NOT NULL,
    time DATETIME NOT NULL,
    text TEXT NOT NULL,

    PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS CAPTCHA_CODES(
    id INT NOT NULL AUTO_INCREMENT,
    time DATETIME NOT NULL,
    code TINYTEXT NOT NULL,
    secret_code TINYTEXT NOT NULL,

    PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS GLOBAL_SETTINGS(
    id INT NOT NULL AUTO_INCREMENT,
    code VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    value VARCHAR(255) NOT NULL,

    PRIMARY KEY(id)
);