ALTER TABLE POSTS
ADD CONSTRAINT FK_POSTS_USER
FOREIGN KEY (moderator_id) REFERENCES USERS(id)
ON DELETE SET NULL;

ALTER TABLE POSTS
ADD CONSTRAINT FK_POSTS_AUTHOR
FOREIGN KEY (user_id) REFERENCES USERS(id)
ON DELETE CASCADE;

ALTER TABLE POST_VOTES
ADD CONSTRAINT FK_POST_VOTES_USER
FOREIGN KEY (user_id) REFERENCES USERS(id)
ON DELETE CASCADE;

ALTER TABLE POST_VOTES
ADD CONSTRAINT FK_POST_VOTES_POST
FOREIGN KEY (post_id) REFERENCES POSTS(id)
ON DELETE CASCADE;

ALTER TABLE TAG2POST
ADD CONSTRAINT FK_TAG2POST_POST
FOREIGN KEY (post_id) REFERENCES POSTS(id)
ON DELETE CASCADE;

ALTER TABLE TAG2POST
ADD CONSTRAINT FK_TAG2POST_TAG
FOREIGN KEY (tag_id) REFERENCES TAGS(id)
ON DELETE CASCADE;

ALTER TABLE POST_COMMENTS
ADD CONSTRAINT FK_POST_COMMENTS_PARENT
FOREIGN KEY (parent_id) REFERENCES POST_COMMENTS(id)
ON DELETE SET NULL;

ALTER TABLE POST_COMMENTS
ADD CONSTRAINT FK_POST_COMMENTS_POST
FOREIGN KEY (post_id) REFERENCES POSTS(id)
ON DELETE CASCADE;

ALTER TABLE POST_COMMENTS
ADD CONSTRAINT FK_POST_COMMENTS_USER
FOREIGN KEY (user_id) REFERENCES USERS(id)
ON DELETE CASCADE;